import hashlib
import hmac
import json
import logging
import os
from typing import Optional

from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException, Header, Query, Request, Response, status
from fastapi.responses import PlainTextResponse

# -----------------------------------------------------------------------------
# 1. Environment & Logging Setup
# -----------------------------------------------------------------------------
# Load environment variables from .env file located in backend directory
load_dotenv()

VERIFY_TOKEN = os.getenv("VERIFY_TOKEN", "")
APP_SECRET = os.getenv("APP_SECRET", "")
SKIP_SIGNATURE_CHECK = os.getenv("SKIP_SIGNATURE_CHECK", "false").lower() in ("true", "1", "yes")

# Configure console logging with standard format and readable timestamps
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
logger = logging.getLogger("meta_ads_webhook")

# Initialize FastAPI application
app = FastAPI(
    title="Meta Lead Ads Webhook Receiver",
    description="Minimal FastAPI application to receive and log Meta Lead Ads webhooks (Day-1 Scope).",
    version="1.0.0",
)


# -----------------------------------------------------------------------------
# 2. Health Check Endpoint
# -----------------------------------------------------------------------------
@app.get("/health", summary="Health Check")
async def health_check():
    """Simple endpoint to verify that the webhook service is running."""
    return {"status": "ok"}


# -----------------------------------------------------------------------------
# 3. Webhook Verification Handshake (GET /webhook)
# -----------------------------------------------------------------------------
@app.get("/webhook", summary="Meta Webhook Verification Handshake")
async def verify_webhook(
    hub_mode: Optional[str] = Query(None, alias="hub.mode"),
    hub_verify_token: Optional[str] = Query(None, alias="hub.verify_token"),
    hub_challenge: Optional[str] = Query(None, alias="hub.challenge"),
):
    """
    Step 1: Meta Verification Handshake.

    When you configure a webhook in Meta App Dashboard, Meta sends a GET request
    with three query parameters:
      - hub.mode: Expected to be 'subscribe'
      - hub.verify_token: A secret token you defined and configured in Meta
      - hub.challenge: A random string generated by Meta

    If the mode is 'subscribe' and the verify_token matches our VERIFY_TOKEN,
    we must return hub.challenge as plain text with status 200.
    """
    logger.info(
        f"Received verification handshake request: mode={hub_mode}, verify_token={'***' if hub_verify_token else None}"
    )

    # Check if verification token matches our expected environment variable
    if hub_mode == "subscribe" and hub_verify_token and VERIFY_TOKEN and hub_verify_token == VERIFY_TOKEN:
        logger.info("Webhook verification handshake successful!")
        # Return the challenge string as a plain-text response
        return PlainTextResponse(content=hub_challenge or "", status_code=status.HTTP_200_OK)

    logger.warning(
        f"Webhook verification failed. Mode: '{hub_mode}', Token match: {hub_verify_token == VERIFY_TOKEN if hub_verify_token and VERIFY_TOKEN else False}"
    )
    raise HTTPException(
        status_code=status.HTTP_403_FORBIDDEN,
        detail="Verification token mismatch or invalid hub.mode",
    )


# -----------------------------------------------------------------------------
# 4. Webhook Notification Receiver (POST /webhook)
# -----------------------------------------------------------------------------
@app.post("/webhook", summary="Meta Webhook Event Receiver")
async def receive_webhook(
    request: Request,
    x_hub_signature_256: Optional[str] = Header(None, alias="X-Hub-Signature-256"),
):
    """
    Step 2 & 3: Signature Verification and Payload Processing.

    When a lead is generated, Meta sends a POST request with:
      1. Header 'X-Hub-Signature-256': Format 'sha256=<hex_digest>'
      2. Request Body (Raw Bytes): HMAC-SHA256 hashed payload using your App Secret.

    Workflow:
      - Read the RAW request body bytes (do NOT parse JSON before verifying).
      - Compute HMAC-SHA256 of raw bytes using APP_SECRET.
      - Compare computed hash against X-Hub-Signature-256 using constant-time comparison (hmac.compare_digest).
      - Parse JSON and extract 'leadgen' events.
      - Log lead details and return 200 OK quickly.
    """
    # Step 2.1: Read raw body bytes for cryptographic signature verification
    raw_body = await request.body()

    # Step 2.2: Signature Verification
    if SKIP_SIGNATURE_CHECK:
        logger.warning("SKIP_SIGNATURE_CHECK is enabled. Bypassing X-Hub-Signature-256 validation (DEBUG ONLY).")
    else:
        if not APP_SECRET:
            logger.error("APP_SECRET is not configured in the environment. Cannot verify signature.")
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail="Server configuration error: APP_SECRET missing",
            )

        if not x_hub_signature_256 or not x_hub_signature_256.startswith("sha256="):
            logger.warning(f"Missing or invalid X-Hub-Signature-256 header: {x_hub_signature_256}")
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail="Missing or malformed X-Hub-Signature-256 header",
            )

        # Compute HMAC-SHA256 signature over the raw payload bytes
        expected_signature = "sha256=" + hmac.new(
            key=APP_SECRET.encode("utf-8"),
            msg=raw_body,
            digestmod=hashlib.sha256,
        ).hexdigest()

        # Constant-time comparison to prevent timing attacks
        if not hmac.compare_digest(expected_signature, x_hub_signature_256):
            logger.warning("HMAC signature verification failed!")
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail="X-Hub-Signature-256 verification failed",
            )
        logger.info("Signature verification passed.")

    # Step 3: Parse JSON Payload
    try:
        payload = json.loads(raw_body.decode("utf-8"))
    except Exception as err:
        logger.error(f"Failed to parse JSON payload: {err}")
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Invalid JSON payload",
        )

    # Log full raw payload once for debugging
    logger.info(f"Received webhook payload: {json.dumps(payload)}")

    # Step 4: Extract Leadgen Events
    # Meta webhook structure for Lead Ads:
    # {
    #   "object": "page",
    #   "entry": [
    #     {
    #       "id": "PAGE_ID",
    #       "time": 1234567890,
    #       "changes": [
    #         {
    #           "field": "leadgen",
    #           "value": {
    #             "leadgen_id": "LEADGEN_ID",
    #             "page_id": "PAGE_ID",
    #             "form_id": "FORM_ID",
    #             "created_time": 1234567890
    #           }
    #         }
    #       ]
    #     }
    #   ]
    # }
    entries = payload.get("entry", [])
    lead_count = 0

    for entry in entries:
        changes = entry.get("changes", [])
        for change in changes:
            field = change.get("field")
            if field == "leadgen":
                lead_count += 1
                value = change.get("value", {})
                leadgen_id = value.get("leadgen_id")
                page_id = value.get("page_id")
                form_id = value.get("form_id")
                created_time = value.get("created_time")

                logger.info(
                    f"🎯 [NEW LEAD DETECTED] leadgen_id={leadgen_id} | page_id={page_id} | form_id={form_id} | created_time={created_time}"
                )

    if lead_count == 0:
        logger.info("No 'leadgen' changes found in this webhook event.")

    # Return 200 OK status quickly to satisfy Meta webhook SLA
    return {"status": "ok"}
